---
name: Publish Subsplits
on:
  push:
    branches:
      - master
  create:
    tags:
      - '0.*'
  delete:
    tags:
      - '0.*'

jobs:
  publish_subsplits:
    runs-on: ubuntu-latest
    name: Publish package sub-splits
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          persist-credentials: 'false'
      - uses: frankdejonge/use-github-token@1.0.2
        with:
          authentication: 'fvdb:${{ secrets.PERSONAL_ACCESS_TOKEN }}'
          user_name: 'Frank van den Brink'
          user_email: 'frank@pragmatist.nl'
      - name: Cache splitsh-lite
        id: splitsh-cache
        uses: actions/cache@v3
        with:
          path: './.splitsh'
          key: '${{ runner.os }}-splitsh'
      - uses: frankdejonge/use-subsplit-publish@1.0.0-beta.7
        with:
          source-branch: 'master'
          config-path: './config.subsplit-publish.json'
          splitsh-path: './.splitsh/splitsh-lite'
          splitsh-version: 'v1.0.1'
